[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps = 
    NimBLE-Arduino=symlink://../../

build_flags = 
    -D CONFIG_BT_ENABLED=1
    -D CONFIG_BT_NIMBLE_ENABLED=1
    -D CORE_DEBUG_LEVEL=4
    -D CONFIG_ENABLE_ARDUINO_DEPENDS=1
    ; Observer-only mode flags
    -D CONFIG_BT_NIMBLE_ROLE_OBSERVER_ONLY=1
    -include "${PROJECT_DIR}/../../src/nimconfig_observer_only.h"
