[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    NimBLE-Arduino=symlink://../../

build_flags = 
    -D CONFIG_BT_NIMBLE_ROLE_OBSERVER_ONLY=1
    -D CONFIG_BT_NIMBLE_ROLE_CENTRAL=0
    -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
    -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER=0
    -D CONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=0
    -D CONFIG_BT_NIMBLE_WHITELIST_SIZE=1
    -D CONFIG_BT_NIMBLE_SM_LEGACY=0
    -D CONFIG_BT_NIMBLE_SM_SC=0
    -D CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM=0