/*
 * NimBLE Observer-Only Configuration
 * 
 * This configuration file aggressively disables all features except
 * passive BLE scanning to minimize flash and RAM usage.
 * 
 * Include this file BEFORE any NimBLE headers in your application:
 * #include "nimconfig_observer_only.h"
 * #include <NimBLEObserverOnly.h>
 * 
 * NOTE: All definitions use #ifndef guards to prevent redefinition warnings
 * when included with ESP-IDF or other configuration headers.
 */

#ifndef NIMCONFIG_OBSERVER_ONLY_H
#define NIMCONFIG_OBSERVER_ONLY_H

// Mark this as observer-only build
#define CONFIG_BT_NIMBLE_ROLE_OBSERVER_ONLY 1

// Disable all roles except observer
#define CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
#define CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED  
#define CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED

// Disable all connection features
#ifndef CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#define CONFIG_BT_NIMBLE_MAX_CONNECTIONS 0
#endif
#ifndef MYNEWT_VAL_BLE_MAX_CONNECTIONS
#define MYNEWT_VAL_BLE_MAX_CONNECTIONS 0
#endif
#ifndef CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM
#define CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM 0
#endif
#ifndef CONFIG_BT_NIMBLE_EATT_CHAN_NUM
#define CONFIG_BT_NIMBLE_EATT_CHAN_NUM 0
#endif

// Disable all security features
#ifndef MYNEWT_VAL_BLE_SM_LVL
#define MYNEWT_VAL_BLE_SM_LVL 0
#endif
#ifndef CONFIG_BT_NIMBLE_SM_LEGACY
#define CONFIG_BT_NIMBLE_SM_LEGACY 0
#endif
#ifndef CONFIG_BT_NIMBLE_SM_SC
#define CONFIG_BT_NIMBLE_SM_SC 0
#endif
#ifndef MYNEWT_VAL_BLE_SM_BONDING
#define MYNEWT_VAL_BLE_SM_BONDING 0
#endif
#ifndef MYNEWT_VAL_BLE_SM_MITM
#define MYNEWT_VAL_BLE_SM_MITM 0
#endif
#ifndef MYNEWT_VAL_BLE_SM_KEYPRESS
#define MYNEWT_VAL_BLE_SM_KEYPRESS 0
#endif
#ifndef MYNEWT_VAL_BLE_SM_OUR_KEY_DIST
#define MYNEWT_VAL_BLE_SM_OUR_KEY_DIST 0
#endif
#ifndef MYNEWT_VAL_BLE_SM_THEIR_KEY_DIST
#define MYNEWT_VAL_BLE_SM_THEIR_KEY_DIST 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_ENCRYPTION
#define MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_ENCRYPTION 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_PING
#define MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_PING 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_DATA_LEN_EXT
#define MYNEWT_VAL_BLE_LL_CFG_FEAT_DATA_LEN_EXT 0
#endif

// Disable store/bonding
#ifndef CONFIG_BT_NIMBLE_NVS_PERSIST
#define CONFIG_BT_NIMBLE_NVS_PERSIST 0
#endif
#ifndef CONFIG_BT_NIMBLE_STORE_CONFIG_DISABLED
#define CONFIG_BT_NIMBLE_STORE_CONFIG_DISABLED 1
#endif
#ifndef CONFIG_BT_NIMBLE_MAX_BONDS
#define CONFIG_BT_NIMBLE_MAX_BONDS 0
#endif
#ifndef MYNEWT_VAL_BLE_STORE_MAX_BONDS
#define MYNEWT_VAL_BLE_STORE_MAX_BONDS 0
#endif
#ifndef CONFIG_BT_NIMBLE_MAX_CCCDS
#define CONFIG_BT_NIMBLE_MAX_CCCDS 0
#endif
#ifndef MYNEWT_VAL_BLE_STORE_MAX_CCCDS
#define MYNEWT_VAL_BLE_STORE_MAX_CCCDS 0
#endif

// Disable GATT client
#define CONFIG_BT_NIMBLE_GATT_MAX_PROCS 0
#define MYNEWT_VAL_BLE_GATT_DISC_ALL_SVCS 0
#define MYNEWT_VAL_BLE_GATT_DISC_ALL_CHRS 0
#define MYNEWT_VAL_BLE_GATT_DISC_ALL_DSCS 0
#define MYNEWT_VAL_BLE_GATT_READ 0
#define MYNEWT_VAL_BLE_GATT_READ_LONG 0
#define MYNEWT_VAL_BLE_GATT_READ_MULT 0
#define MYNEWT_VAL_BLE_GATT_READ_UUID 0
#define MYNEWT_VAL_BLE_GATT_WRITE 0
#define MYNEWT_VAL_BLE_GATT_WRITE_LONG 0
#define MYNEWT_VAL_BLE_GATT_WRITE_NO_RSP 0
#define MYNEWT_VAL_BLE_GATT_WRITE_RELIABLE 0
#define MYNEWT_VAL_BLE_GATT_NOTIFY 0
#define MYNEWT_VAL_BLE_GATT_INDICATE 0
#define CONFIG_BT_NIMBLE_GATT_CACHING 0

// Disable GATT server
#define MYNEWT_VAL_BLE_ATT_SVR_FIND_INFO 0
#define MYNEWT_VAL_BLE_ATT_SVR_FIND_TYPE 0
#define MYNEWT_VAL_BLE_ATT_SVR_INDICATE 0
#define MYNEWT_VAL_BLE_ATT_SVR_NOTIFY 0
#define MYNEWT_VAL_BLE_ATT_SVR_READ 0
#define MYNEWT_VAL_BLE_ATT_SVR_READ_BLOB 0
#define MYNEWT_VAL_BLE_ATT_SVR_READ_GROUP 0
#define MYNEWT_VAL_BLE_ATT_SVR_READ_MULT 0
#define MYNEWT_VAL_BLE_ATT_SVR_READ_TYPE 0
#define MYNEWT_VAL_BLE_ATT_SVR_WRITE 0
#define MYNEWT_VAL_BLE_ATT_SVR_WRITE_CMD 0
#define MYNEWT_VAL_BLE_ATT_SVR_WRITE_NO_RSP 0
#define MYNEWT_VAL_BLE_ATT_SVR_SIGNED_WRITE 0
#define MYNEWT_VAL_BLE_ATT_SVR_PREP_WRITE 0
#define MYNEWT_VAL_BLE_ATT_SVR_EXEC_WRITE 0
#define MYNEWT_VAL_BLE_ATT_SVR_NOTIFY_MULT 0
#define MYNEWT_VAL_BLE_ATT_SVR_QUEUED_WRITE 0
#define MYNEWT_VAL_BLE_ATT_SVR_MAX_PREP_ENTRIES 0

// Disable privacy features
#ifndef CONFIG_BT_NIMBLE_HOST_PRIVACY_DISABLED
#define CONFIG_BT_NIMBLE_HOST_PRIVACY_DISABLED 1
#endif
#ifndef MYNEWT_VAL_BLE_HOST_BASED_PRIVACY
#define MYNEWT_VAL_BLE_HOST_BASED_PRIVACY 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_LL_PRIVACY
#define MYNEWT_VAL_BLE_LL_CFG_FEAT_LL_PRIVACY 0
#endif

// Enable whitelist for hardware filtering in observer mode
// This is useful for filtering devices at the controller level
#ifndef CONFIG_BT_NIMBLE_WHITELIST_SIZE
#define CONFIG_BT_NIMBLE_WHITELIST_SIZE 12
#endif

// Disable advertising extensions
#ifndef CONFIG_BT_NIMBLE_EXT_ADV
#define CONFIG_BT_NIMBLE_EXT_ADV 0
#endif
#ifndef CONFIG_BT_NIMBLE_ENABLE_PERIODIC_ADV
#define CONFIG_BT_NIMBLE_ENABLE_PERIODIC_ADV 0
#endif
#ifndef MYNEWT_VAL_BLE_EXT_ADV
#define MYNEWT_VAL_BLE_EXT_ADV 0
#endif
#ifndef MYNEWT_VAL_BLE_PERIODIC_ADV
#define MYNEWT_VAL_BLE_PERIODIC_ADV 0
#endif
#ifndef MYNEWT_VAL_BLE_MAX_EXT_ADV_INSTANCES
#define MYNEWT_VAL_BLE_MAX_EXT_ADV_INSTANCES 0
#endif

// Reduce buffers
#ifndef CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT
#define CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT 4
#endif
#ifndef CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT
#define CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT 4
#endif
#ifndef CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT
#define CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT 8
#endif

// Disable flow control
#ifndef MYNEWT_VAL_BLE_HS_FLOW_CTRL
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL 0
#endif
#ifndef MYNEWT_VAL_BLE_HS_FLOW_CTRL_ITVL
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL_ITVL 0
#endif
#ifndef MYNEWT_VAL_BLE_HS_FLOW_CTRL_THRESH
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL_THRESH 0
#endif
#ifndef MYNEWT_VAL_BLE_HS_FLOW_CTRL_TX_ON_DISCONNECT
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL_TX_ON_DISCONNECT 0
#endif

// Disable PHY support
#ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_2M_PHY
#define MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_2M_PHY 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_CODED_PHY
#define MYNEWT_VAL_BLE_LL_CFG_FEAT_LE_CODED_PHY 0
#endif

// Disable connection parameter request
#ifndef MYNEWT_VAL_BLE_LL_CFG_FEAT_CONN_PARAM_REQ
#define MYNEWT_VAL_BLE_LL_CFG_FEAT_CONN_PARAM_REQ 0
#endif

// Disable unused features
#ifndef MYNEWT_VAL_BLE_MONITOR
#define MYNEWT_VAL_BLE_MONITOR 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_DTM
#define MYNEWT_VAL_BLE_LL_DTM 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_DTM_UART_BAUD
#define MYNEWT_VAL_BLE_LL_DTM_UART_BAUD 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_DTM_UART_PORT
#define MYNEWT_VAL_BLE_LL_DTM_UART_PORT 0
#endif

// Minimal HCI command/event support
#ifndef MYNEWT_VAL_BLE_LL_NUM_COMP_PKT_RATE
#define MYNEWT_VAL_BLE_LL_NUM_COMP_PKT_RATE 0
#endif
#ifndef MYNEWT_VAL_BLE_LL_CONN_INIT_SLOTS
#define MYNEWT_VAL_BLE_LL_CONN_INIT_SLOTS 0
#endif

// Include base nimconfig for any remaining settings
#include "nimconfig.h"

#endif // NIMCONFIG_OBSERVER_ONLY_H