[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    ../
build_flags = 
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_ONLY
src_filter = +<*> -<main_full.cpp>

[env:esp32dev_full]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    ../
src_filter = +<*> -<main_observer.cpp>